import { defaultConfiguration } from '../domain/configuration-defaults.js';
import { rankingFactors } from '../domain/configuration.js';
import { dynamicRanges, resolutions, sourceTypes, videoCodecs } from '../domain/release.js';

const checkboxGroup = (name: string, values: readonly string[]): string =>
  values
    .map(
      (value) =>
        `<label class="chip"><input type="checkbox" name="${name}" value="${value}" checked> ${value}</label>`,
    )
    .join('');

export function configurePage(nonce: string, configId?: string): string {
  const nonceAttribute = ` nonce="${nonce}"`;
  const defaults = JSON.stringify(defaultConfiguration()).replaceAll('<', '\\u003c');
  const ranking = rankingFactors
    .map(
      (factor) =>
        `<li draggable="true" data-factor="${factor}"><span>${factor}</span><span><button class="rank" data-direction="up" type="button" aria-label="Move ${factor} up">Up</button><button class="rank" data-direction="down" type="button" aria-label="Move ${factor} down">Down</button></span></li>`,
    )
    .join('');
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>CZ/SK Streams configuration</title>
<style${nonceAttribute}>
:root{color-scheme:dark;--bg:#0c111b;--panel:#151d2b;--line:#2b3950;--text:#edf3ff;--muted:#9badc7;--accent:#69e0b4;--danger:#ff8394}*{box-sizing:border-box}body{margin:0;background:linear-gradient(145deg,#09101b,#111827);color:var(--text);font:15px/1.45 system-ui,sans-serif}main{width:min(1050px,calc(100% - 28px));margin:32px auto 70px}header{margin-bottom:24px}h1{font-size:clamp(1.8rem,5vw,3rem);margin:.1em 0}h2{font-size:1.05rem;margin:0 0 16px}.lead,.hint{color:var(--muted)}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.card{background:rgba(21,29,43,.94);border:1px solid var(--line);border-radius:16px;padding:20px;margin-bottom:16px}.wide{grid-column:1/-1}.fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}label{display:grid;gap:6px;color:var(--muted)}input,select,button{font:inherit}input[type=text],input[type=password],input[type=number],select{width:100%;background:#0c1421;color:var(--text);border:1px solid var(--line);border-radius:9px;padding:10px}input:focus,select:focus,button:focus{outline:2px solid var(--accent);outline-offset:2px}.toggle,.chip{display:flex;align-items:center;gap:8px}.chips{display:flex;flex-wrap:wrap;gap:8px}.chip{background:#0c1421;border:1px solid var(--line);border-radius:999px;padding:7px 10px;color:var(--text)}button,.button{border:0;border-radius:10px;background:var(--accent);color:#06251b;font-weight:750;padding:11px 16px;cursor:pointer;text-decoration:none;display:inline-block}.secondary{background:#26354c;color:var(--text)}.danger{background:transparent;color:var(--danger);border:1px solid var(--danger)}.actions{display:flex;flex-wrap:wrap;gap:10px;position:sticky;bottom:0;padding:14px;background:rgba(12,17,27,.95);border:1px solid var(--line);border-radius:14px}.status{min-height:22px;color:var(--accent)}.provider-status{font-size:.86rem;color:var(--muted)}ul{list-style:none;padding:0;margin:0;display:grid;grid-template-columns:repeat(2,1fr);gap:7px}li{background:#0c1421;border:1px solid var(--line);border-radius:8px;padding:7px 9px;cursor:grab;display:flex;align-items:center;justify-content:space-between}.rank{padding:4px 8px;margin-left:4px;background:#26354c;color:var(--text)}li.dragging{opacity:.4}@media(max-width:700px){main{margin-top:18px}.grid,.fields{grid-template-columns:1fr}.wide{grid-column:auto}.card{padding:16px}ul{grid-template-columns:1fr}.actions{position:static}}
</style></head><body><main data-config-id="${configId ?? ''}"><header><p class="hint">Stremio / Nuvio addon</p><h1>CZ/SK Streams</h1><p class="lead">Private, per-user provider configuration. Saved secrets are never loaded back into this page.</p></header>
<form id="configuration"><div class="grid">
<section class="card"><h2>General</h2><div class="fields"><label>Result limit<input name="resultLimit" type="number" min="1" max="100"></label><label>Metadata language<input name="metadataLanguage" type="text" maxlength="16"></label></div></section>
<section class="card"><h2>Display</h2><label>Result formatting<select name="displayMode"><option value="detailed">Detailed</option><option value="compact">Compact</option></select></label></section>
<section class="card"><h2>TMDB metadata</h2><label>API Read Access Token<input autocomplete="new-password" name="tmdbAccessToken" type="password"></label><label class="toggle"><input type="checkbox" name="removeTmdb"> Remove saved token</label><p class="provider-status" data-status="tmdb">Not configured</p><button class="secondary test" data-provider="tmdb" type="button">Test TMDB</button></section>
<section class="card"><h2>SKTorrent</h2><label class="toggle"><input type="checkbox" name="sktorrentEnabled"> Enabled</label><label>Playback<select name="playbackMode"><option value="direct-torrent">Direct torrent</option><option value="torbox-only">TorBox only</option></select></label><label>Username<input autocomplete="username" name="sktorrentUsername" type="text"></label><label>Password<input autocomplete="new-password" name="sktorrentPassword" type="password"></label><label class="toggle"><input type="checkbox" name="removeSktorrent"> Remove saved credentials</label><p class="provider-status" data-status="sktorrent">Not configured</p><button class="secondary test" data-provider="sktorrent" type="button">Test connection</button></section>
<section class="card"><h2>Webshare</h2><label class="toggle"><input type="checkbox" name="webshareEnabled"> Enabled</label><label>Username<input autocomplete="username" name="webshareUsername" type="text"></label><label>Password<input autocomplete="new-password" name="websharePassword" type="password"></label><label class="toggle"><input type="checkbox" name="removeWebshare"> Remove saved credentials</label><p class="provider-status" data-status="webshare">Not configured</p><button class="secondary test" data-provider="webshare" type="button">Test connection</button></section>
<section class="card wide"><h2>TorBox</h2><div class="fields"><label>API key<input autocomplete="new-password" name="torboxApiKey" type="password"></label><label>Precache count<input name="precacheCount" type="number" min="0" max="10"></label><label>Maximum torrent GiB<input name="maximumTorrentGiB" type="number" min="0" step="0.1"></label><label>Maximum total GiB<input name="maximumTotalGiB" type="number" min="0" step="0.1"></label><label>Minimum precache seeders<input name="precacheSeeders" type="number" min="0"></label><label class="toggle"><input type="checkbox" name="showUncached"> Show uncached</label><label class="toggle"><input type="checkbox" name="preferredLanguagesOnly"> Preferred languages only</label><label class="toggle"><input type="checkbox" name="removeTorbox"> Remove saved API key</label></div><p class="provider-status" data-status="torbox">Not configured</p><button class="secondary test" data-provider="torbox" type="button">Test TorBox</button></section>
<section class="card wide"><h2>Filters</h2><p class="hint">Resolution</p><div class="chips">${checkboxGroup('resolutions', resolutions)}</div><p class="hint">Source quality</p><div class="chips">${checkboxGroup('sources', sourceTypes)}</div><p class="hint">Video codecs</p><div class="chips">${checkboxGroup('videoCodecs', videoCodecs)}</div><p class="hint">HDR</p><div class="chips">${checkboxGroup('dynamicRanges', dynamicRanges)}</div><div class="fields"><label>Minimum size GiB<input name="minimumSizeGiB" type="number" min="0" step="0.1"></label><label>Maximum size GiB<input name="maximumSizeGiB" type="number" min="0" step="0.1"></label><label>Minimum seeders<input name="minimumSeeders" type="number" min="0"></label><label>Include terms (comma separated)<input name="includeTerms" type="text"></label><label>Exclude terms (comma separated)<input name="excludeTerms" type="text"></label></div></section>
<section class="card"><h2>Languages</h2><label>Behavior<select name="languageMode"><option value="fallback">Fallback</option><option value="strict">Strict</option></select></label><label>Preferred audio<input name="audioPreferred" type="text"></label><label>Allowed audio<input name="audioAllowed" type="text"></label><label>Excluded audio<input name="audioExcluded" type="text"></label><label>Preferred subtitles<input name="subtitlePreferred" type="text"></label><label>Allowed subtitles<input name="subtitleAllowed" type="text"></label><label>Excluded subtitles<input name="subtitleExcluded" type="text"></label></section>
<section class="card"><h2>Sorting</h2><p class="hint">Drag priorities, or tap one to move it up.</p><ul id="ranking">${ranking}</ul></section>
<section class="card wide"><h2>Advanced</h2><div class="fields"><label>Provider timeout (ms)<input name="providerTimeoutMs" type="number" min="1000" max="60000"></label><label class="toggle"><input type="checkbox" name="safeDebug"> Safe debug metadata (never secrets)</label></div></section>
</div><p class="status" id="message" role="status"></p><div class="actions"><button type="submit">Save</button><a class="button secondary" id="install" hidden>Install in Stremio</a><button class="secondary" id="copy" type="button" hidden>Copy manifest URL</button><button class="danger" id="revoke" type="button" hidden>Revoke configuration</button></div></form></main>
<script${nonceAttribute}>
const defaults=${defaults};const main=document.querySelector('main');const form=document.querySelector('form');const message=document.querySelector('#message');let configId=main.dataset.configId;let manifestUrl='';
const field=n=>form.elements.namedItem(n);const csv=v=>v.split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);const checked=n=>[...form.querySelectorAll('input[name="'+n+'"]:checked')].map(x=>x.value);const gib=n=>{const v=Number(field(n).value);return v>0?Math.round(v*1073741824):undefined};
function populate(c){field('resultLimit').value=c.limits.total;field('metadataLanguage').value=c.general?.metadataLanguage??'sk-SK';field('displayMode').value=c.display.mode;field('sktorrentEnabled').checked=c.providers.sktorrent.enabled;field('playbackMode').value=c.providers.sktorrent.playbackMode;field('webshareEnabled').checked=c.providers.webshare.enabled;field('precacheCount').value=c.torbox.precacheCount;field('showUncached').checked=c.torbox.showUncached;field('maximumTorrentGiB').value=c.torbox.precacheLimits?.maximumTorrentSizeBytes/1073741824||'';field('maximumTotalGiB').value=c.torbox.precacheLimits?.maximumTotalSizeBytes/1073741824||'';field('precacheSeeders').value=c.torbox.precacheLimits?.minimumSeeders??'';field('preferredLanguagesOnly').checked=c.torbox.precacheLimits?.preferredLanguagesOnly??false;for(const n of ['resolutions','sources','videoCodecs','dynamicRanges'])for(const x of form.querySelectorAll('input[name="'+n+'"]'))x.checked=c.filters[n].includes(x.value);field('minimumSizeGiB').value=c.filters.minimumSizeBytes/1073741824||'';field('maximumSizeGiB').value=c.filters.maximumSizeBytes/1073741824||'';field('minimumSeeders').value=c.filters.minimumSeeders;field('includeTerms').value=c.filters.includeTerms.join(', ');field('excludeTerms').value=c.filters.excludeTerms.join(', ');field('languageMode').value=c.languages.mode;for(const [n,v] of [['audioPreferred',c.languages.audio.preferred],['audioAllowed',c.languages.audio.allowed],['audioExcluded',c.languages.audio.excluded],['subtitlePreferred',c.languages.subtitles.preferred],['subtitleAllowed',c.languages.subtitles.allowed],['subtitleExcluded',c.languages.subtitles.excluded]])field(n).value=v.join(', ');field('providerTimeoutMs').value=c.advanced?.providerTimeoutMs??8000;field('safeDebug').checked=c.advanced?.safeDebug??false;const list=document.querySelector('#ranking');for(const factor of c.ranking){const item=list.querySelector('[data-factor="'+factor+'"]');if(item)list.append(item)}}
function payload(){const limit=(key,value)=>value===undefined?{}:{[key]:value};const credentials={};if(field('removeTmdb').checked)credentials.tmdb=null;else if(field('tmdbAccessToken').value.trim())credentials.tmdb={accessToken:field('tmdbAccessToken').value.trim()};for(const p of ['sktorrent','webshare']){if(field('remove'+p[0].toUpperCase()+p.slice(1)).checked)credentials[p]=null;else{const username=field(p+'Username').value.trim(),password=field(p+'Password').value;if(username&&password)credentials[p]={username,password}}}if(field('removeTorbox').checked)credentials.torbox=null;else if(field('torboxApiKey').value.trim())credentials.torbox={apiKey:field('torboxApiKey').value.trim()};return{configuration:{general:{metadataLanguage:field('metadataLanguage').value.trim()},providers:{sktorrent:{enabled:field('sktorrentEnabled').checked,playbackMode:field('playbackMode').value},webshare:{enabled:field('webshareEnabled').checked}},filters:{resolutions:checked('resolutions'),sources:checked('sources'),videoCodecs:checked('videoCodecs'),dynamicRanges:checked('dynamicRanges'),...limit('minimumSizeBytes',gib('minimumSizeGiB')),...limit('maximumSizeBytes',gib('maximumSizeGiB')),minimumSeeders:Number(field('minimumSeeders').value),includeTerms:csv(field('includeTerms').value),excludeTerms:csv(field('excludeTerms').value)},languages:{mode:field('languageMode').value,audio:{preferred:csv(field('audioPreferred').value),allowed:csv(field('audioAllowed').value),excluded:csv(field('audioExcluded').value)},subtitles:{preferred:csv(field('subtitlePreferred').value),allowed:csv(field('subtitleAllowed').value),excluded:csv(field('subtitleExcluded').value)}},ranking:[...document.querySelectorAll('#ranking li')].map(x=>x.dataset.factor),limits:{total:Number(field('resultLimit').value),perResolution:{}},torbox:{showUncached:field('showUncached').checked,precacheCount:Number(field('precacheCount').value),precacheLimits:{...limit('minimumSeeders',field('precacheSeeders').value===''?undefined:Number(field('precacheSeeders').value)),...limit('maximumTorrentSizeBytes',gib('maximumTorrentGiB')),...limit('maximumTotalSizeBytes',gib('maximumTotalGiB')),preferredLanguagesOnly:field('preferredLanguagesOnly').checked}},display:{mode:field('displayMode').value},advanced:{providerTimeoutMs:Number(field('providerTimeoutMs').value),safeDebug:field('safeDebug').checked}},credentials}};
function show(data){configId=data.id;manifestUrl=data.manifestUrl;history.replaceState(null,'','/configure/'+configId);for(const p of ['tmdb','sktorrent','webshare','torbox'])document.querySelector('[data-status="'+p+'"]').textContent=data.credentials[p].configured?'Saved '+data.credentials[p].masked:'Not configured';document.querySelector('#install').hidden=false;document.querySelector('#install').href='stremio://'+manifestUrl.replace('https://','').replace('http://','');document.querySelector('#copy').hidden=false;document.querySelector('#revoke').hidden=false;for(const n of ['tmdbAccessToken','sktorrentPassword','websharePassword','torboxApiKey'])field(n).value='';}
async function request(url,options){const response=await fetch(url,options);const data=await response.json();if(!response.ok)throw new Error(data.error||'Request failed');return data}
form.addEventListener('submit',async e=>{e.preventDefault();message.textContent='Saving...';try{const data=await request(configId?'/api/configurations/'+configId:'/api/configurations',{method:configId?'PUT':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload())});show(data);message.textContent='Configuration saved.'}catch(e){message.textContent=e.message}});
document.querySelectorAll('.test').forEach(button=>button.addEventListener('click',async()=>{message.textContent='Testing...';try{await request('/api/provider-tests/'+button.dataset.provider,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...payload().credentials,configurationId:configId||undefined})});message.textContent='Connection successful.'}catch(e){message.textContent=e.message}}));
document.querySelector('#copy').addEventListener('click',async()=>{await navigator.clipboard.writeText(manifestUrl);message.textContent='Manifest URL copied.'});document.querySelector('#revoke').addEventListener('click',async()=>{if(!confirm('Revoke this configuration?'))return;await request('/api/configurations/'+configId,{method:'DELETE'});location.href='/configure'});
let dragged;document.querySelector('#ranking').addEventListener('dragstart',e=>{dragged=e.target.closest('li');dragged?.classList.add('dragging')});document.querySelector('#ranking').addEventListener('dragend',()=>dragged?.classList.remove('dragging'));document.querySelector('#ranking').addEventListener('dragover',e=>{e.preventDefault();const target=e.target.closest('li');if(target&&dragged&&target!==dragged)target.before(dragged)});
document.querySelectorAll('.rank').forEach(button=>button.addEventListener('click',()=>{const item=button.closest('li');if(button.dataset.direction==='up'&&item.previousElementSibling)item.previousElementSibling.before(item);if(button.dataset.direction==='down'&&item.nextElementSibling)item.nextElementSibling.after(item)}));
populate(defaults);if(configId)request('/api/configurations/'+configId).then(data=>{populate(data.configuration);show(data)}).catch(e=>message.textContent=e.message);
</script></body></html>`;
}
